---
title: "`MortalityLaws` Installation"
author: "Marius D. Pascariu"
date: "December 1, 2017"
output: 
  pdf_document:
    number_sections: true
vignette: >
  %\VignetteIndexEntry{MortalityLaws Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Install stable version from `CRAN`

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

The `pclm` package can be installed from [`CRAN`](https://cran.r-project.org/web/packages/MortalityLaws/index.html) as follows:

1. Make sure you have the most recent version of R
2. Run the following code in your R console 

```{r, eval=FALSE}
install.packages("MortalityLaws")
```

# Install development version from `GitHub`
The latest version can be installed from author's [`GitHub repository`](https://github.com/mpascariu/MortalityLaws) by running the following code in your R console:

```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("mpascariu/MortalityLaws")
```

