# --------------------------------------------
# Author: Marius D PASCARIU
# Date: 2026-05-04 23:30:36
# --------------------------------------------

#' MortalityLaws Test Data
#'
#' Dataset containing altered death rates (mx), death counts (Dx)
#' and exposures (Ex) for the female population living in
#' England & Wales in four different years: 1850, 1900, 1950 and 2010.
#' This dataset is provided for testing purposes only.
#' Download the actual data free of charge from \url{https://www.mortality.org}.
#' Once a username and a password are created on the website, the function
#' \code{\link{ReadHMD}} can be used for downloading.
#'
#' @format A list with the components \code{mx}, \code{Dx} and \code{Ex}.
#'   Each component is a \code{data.frame} with 111 rows (ages 0 to 110) and
#'   one column per year: 1850, 1900, 1950 and 2010.
#' @source \href{https://www.mortality.org}{Human Mortality Database}
#' @seealso \code{\link{ReadHMD}}
#' @examples head(ahmd$mx)
"ahmd"


#' HMD sample
#' Data object generated by the \code{ReadHMD()} function.
#' @format A list of class \code{ReadHMD} with the following components:
#' \describe{
#'   \item{input}{A list with the arguments used in the call to
#'     \code{\link{ReadHMD}}.}
#'   \item{data}{A \code{data.frame} with the columns \code{country},
#'     \code{Year}, \code{Age}, \code{Female}, \code{Male} and \code{Total}.}
#'   \item{download.date}{A character string with the date of the download.}
#'   \item{years}{An integer vector with the years covered by the sample.}
#'   \item{ages}{An integer vector with the ages covered by the sample.}
#' }
#' @keywords internal
"HMD_sample"

#' AHMD sample
#' Data object generated by the \code{ReadAHMD()} function.
#' @format A list of class \code{ReadAHMD} with the following components:
#' \describe{
#'   \item{input}{A list with the arguments used in the call to
#'     \code{\link{ReadAHMD}}.}
#'   \item{data}{A \code{data.frame} with the columns \code{country},
#'     \code{Year}, \code{Age}, \code{Female}, \code{Male} and \code{Total}.}
#'   \item{download.date}{A character string with the date of the download.}
#'   \item{years}{An integer vector with the years covered by the sample.}
#'   \item{ages}{A character vector with the ages covered by the sample.}
#' }
#' @keywords internal
"AHMD_sample"

#' CHMD sample
#' Data object generated by the \code{ReadCHMD()} function.
#' @format A list of class \code{ReadCHMD} with the following components:
#' \describe{
#'   \item{input}{A list with the arguments used in the call to
#'     \code{\link{ReadCHMD}}.}
#'   \item{data}{A \code{data.frame} with the columns \code{country},
#'     \code{Year}, \code{Age}, \code{Female}, \code{Male} and \code{Total}.}
#'   \item{download.date}{A character string with the date of the download.}
#'   \item{years}{An integer vector with the years covered by the sample.}
#'   \item{ages}{A character vector with the ages covered by the sample.}
#' }
#' @keywords internal
"CHMD_sample"

#' JMD sample
#' Data object generated by the \code{ReadJMD()} function.
#' @format A list of class \code{ReadJMD} with the following components:
#' \describe{
#'   \item{input}{A list with the arguments used in the call to
#'     \code{\link{ReadJMD}}.}
#'   \item{data}{A \code{data.frame} with the columns \code{region},
#'     \code{Year}, \code{Age}, \code{Female}, \code{Male} and \code{Total}.}
#'   \item{download.date}{A character string with the date of the download.}
#'   \item{years}{An integer vector with the years covered by the sample.}
#'   \item{ages}{A character vector with the ages covered by the sample.}
#' }
#' @keywords internal
"JMD_sample"


